In [1]:
from pathlib import Path
import pandas as pd

project_path = Path(r"C:\Projects\Harsh Retail Analytics Capstone")
file_path = project_path / "Raw Data" / "online_retail_II.xlsx"

print(file_path)
print(file_path.exists())

C:\Projects\Harsh Retail Analytics Capstone\Raw Data\online_retail_II.xlsx
False

In [2]:
raw_data_path = project_path / "Raw Data"

for item in raw_data_path.iterdir():
    print(repr(item.name))

'online_retail_II.xlsx.xlsx'

In [3]:
files = list(raw_data_path.iterdir())

print(files)

old_file = files[0]
correct_file = raw_data_path / "online_retail_II.xlsx"

if old_file != correct_file:
    old_file.rename(correct_file)

print(correct_file)
print(correct_file.exists())

[WindowsPath('C:/Projects/Harsh Retail Analytics Capstone/Raw Data/online_retail_II.xlsx.xlsx')]
C:\Projects\Harsh Retail Analytics Capstone\Raw Data\online_retail_II.xlsx
True

In [4]:
file_path = project_path / "Raw Data" / "online_retail_II.xlsx"

print(file_path)
print(file_path.exists())

C:\Projects\Harsh Retail Analytics Capstone\Raw Data\online_retail_II.xlsx
True

In [5]:
excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)

['Year 2009-2010', 'Year 2010-2011']

In [6]:
for sheet_name in excel_file.sheet_names:
    preview = pd.read_excel(
        file_path,
        sheet_name=sheet_name,
        nrows=5
    )

    print("Sheet:", sheet_name)
    print("Rows shown:", len(preview))
    display(preview)

Sheet: Year 2009-2010
Rows shown: 5

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

Sheet: Year 2010-2011
Rows shown: 5

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [7]:
for sheet_name in excel_file.sheet_names:
    preview = pd.read_excel(
        file_path,
        sheet_name=sheet_name,
        nrows=5
    )

    print("Sheet:", sheet_name)
    print("Columns:")
    print(list(preview.columns))
    print()

Sheet: Year 2009-2010
Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Sheet: Year 2010-2011
Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [8]:
dataframes = []

for sheet_name in excel_file.sheet_names:
    sheet_data = pd.read_excel(
        file_path,
        sheet_name=sheet_name
    )

    sheet_data["SourceYear"] = sheet_name
    dataframes.append(sheet_data)

raw_df = pd.concat(
    dataframes,
    ignore_index=True
)

print("Rows:", f"{len(raw_df):,}")
print("Columns:", raw_df.shape[1])
print("Memory usage in MB:", round(
    raw_df.memory_usage(deep=True).sum() / 1024**2,
    2
))

display(raw_df.head())

Rows: 1,067,371
Columns: 9
Memory usage in MB: 313.18

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,SourceYear
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Year 2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Year 2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Year 2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Year 2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Year 2009-2010

In [9]:
audit_table = pd.DataFrame({
    "Column": raw_df.columns,
    "DataType": raw_df.dtypes.astype(str).values,
    "MissingValues": raw_df.isna().sum().values,
    "MissingPercent": (
        raw_df.isna().mean() * 100
    ).round(2).values,
    "UniqueValues": raw_df.nunique(
        dropna=False
    ).values
})

display(audit_table)

        Column        DataType  MissingValues  MissingPercent  UniqueValues
0      Invoice          object              0            0.00         53628
1    StockCode          object              0            0.00          5305
2  Description          object           4382            0.41          5699
3     Quantity           int64              0            0.00          1057
4  InvoiceDate  datetime64[us]              0            0.00         47635
5        Price         float64              0            0.00          2807
6  Customer ID         float64         243007           22.77          5943
7      Country             str              0            0.00            43
8   SourceYear             str              0            0.00             2

In [10]:
print(
    "Exact duplicate rows:",
    f"{raw_df.duplicated().sum():,}"
)

print(
    "First transaction date:",
    raw_df["InvoiceDate"].min()
)

print(
    "Last transaction date:",
    raw_df["InvoiceDate"].max()
)

cancelled_rows = (
    raw_df["Invoice"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

negative_quantity_rows = (
    raw_df["Quantity"] < 0
).sum()

zero_or_negative_price_rows = (
    raw_df["Price"] <= 0
).sum()

print(
    "Cancelled invoice rows:",
    f"{cancelled_rows:,}"
)

print(
    "Negative quantity rows:",
    f"{negative_quantity_rows:,}"
)

print(
    "Zero or negative price rows:",
    f"{zero_or_negative_price_rows:,}"
)

Exact duplicate rows: 12,133
First transaction date: 2009-12-01 07:45:00
Last transaction date: 2011-12-09 12:50:00
Cancelled invoice rows: 19,494
Negative quantity rows: 22,950
Zero or negative price rows: 6,207

In [11]:
clean_base = raw_df.copy()

clean_base = clean_base.rename(columns={
    "Invoice": "invoice",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "InvoiceDate": "invoice_date",
    "Price": "unit_price",
    "Customer ID": "customer_id",
    "Country": "country",
    "SourceYear": "source_year"
})

text_columns = [
    "invoice",
    "stock_code",
    "description",
    "country",
    "source_year"
]

for column in text_columns:
    clean_base[column] = (
        clean_base[column]
        .astype("string")
        .str.strip()
    )

clean_base["is_cancelled"] = (
    clean_base["invoice"]
    .str.startswith("C", na=False)
)

clean_base["is_negative_quantity"] = (
    clean_base["quantity"] < 0
)

clean_base["is_non_positive_price"] = (
    clean_base["unit_price"] <= 0
)

clean_base["is_missing_description"] = (
    clean_base["description"].isna()
    | clean_base["description"].eq("")
)

clean_base["is_missing_customer"] = (
    clean_base["customer_id"].isna()
)

print("Cleaning flags created")
display(clean_base.head())

Cleaning flags created

,invoice,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,source_year,is_cancelled,is_negative_quantity,is_non_positive_price,is_missing_description,is_missing_customer
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Year 2009-2010,False,False,False,False,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Year 2009-2010,False,False,False,False,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Year 2009-2010,False,False,False,False,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Year 2009-2010,False,False,False,False,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Year 2009-2010,False,False,False,False,False

In [12]:
sales_mask = (
    clean_base["is_cancelled"].eq(False)
    & clean_base["quantity"].gt(0)
    & clean_base["unit_price"].gt(0)
    & clean_base["is_missing_description"].eq(False)
)

sales_df = (
    clean_base
    .loc[sales_mask]
    .copy()
)

excluded_df = (
    clean_base
    .loc[~sales_mask]
    .copy()
)

sales_df["customer_id"] = (
    sales_df["customer_id"]
    .astype("Int64")
)

sales_df["line_revenue"] = (
    sales_df["quantity"]
    * sales_df["unit_price"]
).round(2)

sales_df["invoice_year"] = (
    sales_df["invoice_date"].dt.year
)

sales_df["invoice_month"] = (
    sales_df["invoice_date"]
    .dt.to_period("M")
    .astype(str)
)

sales_df["invoice_hour"] = (
    sales_df["invoice_date"].dt.hour
)

print(
    "Clean sales rows:",
    f"{len(sales_df):,}"
)

print(
    "Excluded rows:",
    f"{len(excluded_df):,}"
)

display(sales_df.head())

Clean sales rows: 1,041,670
Excluded rows: 25,701

,invoice,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,source_year,is_cancelled,is_negative_quantity,is_non_positive_price,is_missing_description,is_missing_customer,line_revenue,invoice_year,invoice_month,invoice_hour
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,Year 2009-2010,False,False,False,False,False,83.4,2009,2009-12,7
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,Year 2009-2010,False,False,False,False,False,81.0,2009,2009-12,7
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,Year 2009-2010,False,False,False,False,False,81.0,2009,2009-12,7
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,Year 2009-2010,False,False,False,False,False,100.8,2009,2009-12,7
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,Year 2009-2010,False,False,False,False,False,30.0,2009,2009-12,7

In [13]:
customer_df = (
    sales_df
    .dropna(subset=["customer_id"])
    .copy()
)

customer_df["customer_id"] = (
    customer_df["customer_id"]
    .astype("int64")
)

print(
    "Customer analysis rows:",
    f"{len(customer_df):,}"
)

print(
    "Unique customers:",
    f"{customer_df['customer_id'].nunique():,}"
)

Customer analysis rows: 805,549
Unique customers: 5,878

In [14]:
cleaning_summary = pd.DataFrame({
    "metric": [
        "Raw rows",
        "Exact duplicates removed",
        "Rows after duplicate removal",
        "Clean sales rows",
        "Excluded rows",
        "Customer analysis rows",
        "Missing customer rows retained",
        "Unique clean invoices",
        "Unique customers",
        "Total positive revenue"
    ],
    "value": [
        len(raw_df),
        duplicates_removed,
        len(clean_base),
        len(sales_df),
        len(excluded_df),
        len(customer_df),
        sales_df["customer_id"].isna().sum(),
        sales_df["invoice"].nunique(),
        customer_df["customer_id"].nunique(),
        round(sales_df["line_revenue"].sum(), 2)
    ]
})

display(cleaning_summary)

NameError: name 'duplicates_removed' is not defined

In [15]:
clean_data_path = project_path / "Clean Data"

clean_data_path.mkdir(
    parents=True,
    exist_ok=True
)

sales_df.to_csv(
    clean_data_path
    / "clean_sales_transactions.csv",
    index=False
)

customer_df.to_csv(
    clean_data_path
    / "customer_transactions.csv",
    index=False
)

excluded_df.to_csv(
    clean_data_path
    / "excluded_records_with_flags.csv",
    index=False
)

cleaning_summary.to_csv(
    clean_data_path
    / "cleaning_summary.csv",
    index=False
)

print("Files saved successfully")

for file in clean_data_path.iterdir():
    print(file.name)

NameError: name 'cleaning_summary' is not defined

In [16]:
cleaning_summary = pd.DataFrame({
    "metric": [
        "Raw rows",
        "Exact duplicates removed",
        "Rows after duplicate removal",
        "Clean sales rows",
        "Excluded rows",
        "Customer analysis rows",
        "Missing customer rows retained",
        "Unique clean invoices",
        "Unique customers",
        "Total positive revenue"
    ],
    "value": [
        len(raw_df),
        duplicates_removed,
        len(clean_base),
        len(sales_df),
        len(excluded_df),
        len(customer_df),
        sales_df["customer_id"].isna().sum(),
        sales_df["invoice"].nunique(),
        customer_df["customer_id"].nunique(),
        round(sales_df["line_revenue"].sum(), 2)
    ]
})

display(cleaning_summary)

NameError: name 'duplicates_removed' is not defined

In [17]:
from pathlib import Path
import pandas as pd

project_path = Path(
    r"C:\Projects\Harsh Retail Analytics Capstone"
)

file_path = (
    project_path
    / "Raw Data"
    / "online_retail_II.xlsx"
)

clean_data_path = project_path / "Clean Data"

clean_data_path.mkdir(
    parents=True,
    exist_ok=True
)

if "raw_df" not in globals():
    excel_file = pd.ExcelFile(file_path)

    dataframes = []

    for sheet_name in excel_file.sheet_names:
        sheet_data = pd.read_excel(
            file_path,
            sheet_name=sheet_name
        )

        sheet_data["SourceYear"] = sheet_name
        dataframes.append(sheet_data)

    raw_df = pd.concat(
        dataframes,
        ignore_index=True
    )

print("Raw rows:", f"{len(raw_df):,}")

clean_base = raw_df.copy()

clean_base = clean_base.rename(columns={
    "Invoice": "invoice",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "InvoiceDate": "invoice_date",
    "Price": "unit_price",
    "Customer ID": "customer_id",
    "Country": "country",
    "SourceYear": "source_year"
})

text_columns = [
    "invoice",
    "stock_code",
    "description",
    "country",
    "source_year"
]

for column in text_columns:
    clean_base[column] = (
        clean_base[column]
        .astype("string")
        .str.strip()
    )

rows_before_duplicates = len(clean_base)

clean_base = (
    clean_base
    .drop_duplicates()
    .copy()
)

duplicates_removed = (
    rows_before_duplicates
    - len(clean_base)
)

clean_base["is_cancelled"] = (
    clean_base["invoice"]
    .str.startswith("C", na=False)
)

clean_base["is_negative_quantity"] = (
    clean_base["quantity"] < 0
)

clean_base["is_non_positive_price"] = (
    clean_base["unit_price"] <= 0
)

clean_base["is_missing_description"] = (
    clean_base["description"].isna()
    | clean_base["description"].eq("")
)

clean_base["is_missing_customer"] = (
    clean_base["customer_id"].isna()
)

sales_mask = (
    clean_base["is_cancelled"].eq(False)
    & clean_base["quantity"].gt(0)
    & clean_base["unit_price"].gt(0)
    & clean_base["is_missing_description"].eq(False)
)

sales_df = (
    clean_base
    .loc[sales_mask]
    .copy()
)

excluded_df = (
    clean_base
    .loc[~sales_mask]
    .copy()
)

sales_df["customer_id"] = (
    sales_df["customer_id"]
    .astype("Int64")
)

sales_df["line_revenue"] = (
    sales_df["quantity"]
    * sales_df["unit_price"]
).round(2)

sales_df["invoice_year"] = (
    sales_df["invoice_date"].dt.year
)

sales_df["invoice_month"] = (
    sales_df["invoice_date"]
    .dt.to_period("M")
    .astype(str)
)

sales_df["invoice_hour"] = (
    sales_df["invoice_date"].dt.hour
)

customer_df = (
    sales_df
    .dropna(subset=["customer_id"])
    .copy()
)

customer_df["customer_id"] = (
    customer_df["customer_id"]
    .astype("int64")
)

cleaning_summary = pd.DataFrame({
    "metric": [
        "Raw rows",
        "Exact duplicates removed",
        "Rows after duplicate removal",
        "Clean sales rows",
        "Excluded rows",
        "Customer analysis rows",
        "Missing customer rows retained",
        "Unique clean invoices",
        "Unique customers",
        "Total positive revenue"
    ],
    "value": [
        len(raw_df),
        duplicates_removed,
        len(clean_base),
        len(sales_df),
        len(excluded_df),
        len(customer_df),
        sales_df["customer_id"].isna().sum(),
        sales_df["invoice"].nunique(),
        customer_df["customer_id"].nunique(),
        round(sales_df["line_revenue"].sum(), 2)
    ]
})

sales_df.to_csv(
    clean_data_path
    / "clean_sales_transactions.csv",
    index=False
)

customer_df.to_csv(
    clean_data_path
    / "customer_transactions.csv",
    index=False
)

excluded_df.to_csv(
    clean_data_path
    / "excluded_records_with_flags.csv",
    index=False
)

cleaning_summary.to_csv(
    clean_data_path
    / "cleaning_summary.csv",
    index=False
)

display(cleaning_summary)

print("\nSaved files:")

for file in clean_data_path.iterdir():
    print(file.name)

Raw rows: 1,067,371

                           metric        value
0                        Raw rows   1067371.00
1        Exact duplicates removed     12133.00
2    Rows after duplicate removal   1055238.00
3                Clean sales rows   1029609.00
4                   Excluded rows     25629.00
5          Customer analysis rows    793609.00
6  Missing customer rows retained    236000.00
7           Unique clean invoices     40077.00
8                Unique customers      5878.00
9          Total positive revenue  20913891.45

Saved files:
cleaning_summary.csv
clean_sales_transactions.csv
customer_transactions.csv
excluded_records_with_flags.csv

In [18]:
validation_results = {
    "No duplicate rows": sales_df.duplicated().sum() == 0,
    "No cancelled invoices": (
        sales_df["invoice"]
        .str.startswith("C", na=False)
        .sum() == 0
    ),
    "All quantities are positive": (
        sales_df["quantity"] <= 0
    ).sum() == 0,
    "All prices are positive": (
        sales_df["unit_price"] <= 0
    ).sum() == 0,
    "No missing descriptions": (
        sales_df["description"].isna().sum() == 0
    ),
    "All revenue values are positive": (
        sales_df["line_revenue"] <= 0
    ).sum() == 0,
    "Customer dataset has no missing IDs": (
        customer_df["customer_id"].isna().sum() == 0
    ),
    "Clean and excluded rows reconcile": (
        len(sales_df) + len(excluded_df)
        == len(clean_base)
    )
}

validation_table = pd.DataFrame({
    "test": validation_results.keys(),
    "passed": validation_results.values()
})

display(validation_table)

print(
    "All validation tests passed:",
    validation_table["passed"].all()
)

print(
    "Sales date range:",
    sales_df["invoice_date"].min(),
    "to",
    sales_df["invoice_date"].max()
)

                                  test  passed
0                    No duplicate rows    True
1                No cancelled invoices    True
2          All quantities are positive    True
3              All prices are positive    True
4              No missing descriptions    True
5      All revenue values are positive   False
6  Customer dataset has no missing IDs    True
7    Clean and excluded rows reconcile    True

All validation tests passed: False
Sales date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00

In [19]:
problem_revenue_rows = sales_df[
    sales_df["line_revenue"] <= 0
]

print(
    "Problem revenue rows:",
    len(problem_revenue_rows)
)

display(
    problem_revenue_rows[
        [
            "invoice",
            "stock_code",
            "quantity",
            "unit_price",
            "line_revenue"
        ]
    ].head(20)
)

Problem revenue rows: 18

       invoice    stock_code  quantity  unit_price  line_revenue
62299   494914          PADS         1       0.001           0.0
74731   496222          PADS         1       0.001           0.0
77702   496473          PADS         1       0.001           0.0
79794   496643          PADS         1       0.001           0.0
90798   497935          PADS         1       0.001           0.0
97716   498562          PADS         1       0.001           0.0
101718  499056          PADS         1       0.001           0.0
104480  499399          PADS         1       0.001           0.0
123947  501176          PADS         1       0.001           0.0
156809  504332          PADS         1       0.001           0.0
178629  506303          PADS         1       0.001           0.0
341826  522766          PADS         1       0.001           0.0
440930  531433          PADS         1       0.001           0.0
468280  533528          PADS         1       0.001           0.0
682656  550193          PADS         1       0.001           0.0
804506  561226          PADS         1       0.001           0.0
885332  568200          PADS         1       0.001           0.0
887202  568375  BANK CHARGES         1       0.001           0.0

In [20]:
sales_df["line_revenue"] = (
    sales_df["quantity"]
    * sales_df["unit_price"]
)

customer_df["line_revenue"] = (
    customer_df["quantity"]
    * customer_df["unit_price"]
)

print(
    "Non positive revenue rows:",
    (sales_df["line_revenue"] <= 0).sum()
)

Non positive revenue rows: 0

In [21]:
cleaning_summary.loc[
    cleaning_summary["metric"]
    == "Total positive revenue",
    "value"
] = sales_df["line_revenue"].sum()

display(cleaning_summary)

                           metric         value
0                        Raw rows  1.067371e+06
1        Exact duplicates removed  1.213300e+04
2    Rows after duplicate removal  1.055238e+06
3                Clean sales rows  1.029609e+06
4                   Excluded rows  2.562900e+04
5          Customer analysis rows  7.936090e+05
6  Missing customer rows retained  2.360000e+05
7           Unique clean invoices  4.007700e+04
8                Unique customers  5.878000e+03
9          Total positive revenue  2.091389e+07

In [22]:
print(
    "Total revenue:",
    round(
        sales_df["line_revenue"].sum(),
        2
    )
)

Total revenue: 20913891.47

In [23]:
sales_df.to_csv(
    clean_data_path
    / "clean_sales_transactions.csv",
    index=False
)

customer_df.to_csv(
    clean_data_path
    / "customer_transactions.csv",
    index=False
)

cleaning_summary.to_csv(
    clean_data_path
    / "cleaning_summary.csv",
    index=False
)

print("Corrected files saved")

Corrected files saved

In [24]:
validation_results = {
    "No duplicate rows": sales_df.duplicated().sum() == 0,
    "No cancelled invoices": (
        sales_df["invoice"]
        .str.startswith("C", na=False)
        .sum() == 0
    ),
    "All quantities are positive": (
        sales_df["quantity"] <= 0
    ).sum() == 0,
    "All prices are positive": (
        sales_df["unit_price"] <= 0
    ).sum() == 0,
    "No missing descriptions": (
        sales_df["description"].isna().sum() == 0
    ),
    "All revenue values are positive": (
        sales_df["line_revenue"] <= 0
    ).sum() == 0,
    "Customer dataset has no missing IDs": (
        customer_df["customer_id"].isna().sum() == 0
    ),
    "Clean and excluded rows reconcile": (
        len(sales_df) + len(excluded_df)
        == len(clean_base)
    )
}

validation_table = pd.DataFrame({
    "test": validation_results.keys(),
    "passed": validation_results.values()
})

display(validation_table)

print(
    "All validation tests passed:",
    validation_table["passed"].all()
)

print(
    "Sales date range:",
    sales_df["invoice_date"].min(),
    "to",
    sales_df["invoice_date"].max()
)

                                  test  passed
0                    No duplicate rows    True
1                No cancelled invoices    True
2          All quantities are positive    True
3              All prices are positive    True
4              No missing descriptions    True
5      All revenue values are positive    True
6  Customer dataset has no missing IDs    True
7    Clean and excluded rows reconcile    True

All validation tests passed: True
Sales date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00

In [25]:
validation_table.to_csv(
    clean_data_path / "validation_report.csv",
    index=False
)

print("Validation report saved")

Validation report saved

In [26]:
%pip install psycopg2_binary

Collecting psycopg2_binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 29.4 MB/s eta 0:00:00
Installing collected packages: psycopg2_binary
Successfully installed psycopg2_binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from pathlib import Path
from getpass import getpass
import psycopg2

csv_path = Path(
    r"C:\Projects\Harsh Retail Analytics Capstone\Clean Data\clean_sales_transactions.csv"
)

postgres_password = getpass(
    "Enter your PostgreSQL password: "
)

conn = psycopg2.connect(
    host="localhost",
    port=5432,
    dbname="retail_capstone",
    user="postgres",
    password=postgres_password
)

print("Connected:", conn.closed == 0)
print("CSV exists:", csv_path.exists())

Enter your PostgreSQL password:  ········

Connected: True
CSV exists: True

In [2]:
copy_sql = """
COPY public.clean_sales_transactions (
    invoice,
    stock_code,
    description,
    quantity,
    invoice_date,
    unit_price,
    customer_id,
    country,
    source_year,
    is_cancelled,
    is_negative_quantity,
    is_non_positive_price,
    is_missing_description,
    is_missing_customer,
    line_revenue,
    invoice_year,
    invoice_month,
    invoice_hour
)
FROM STDIN
WITH (
    FORMAT CSV,
    HEADER TRUE,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"',
    NULL '',
    ENCODING 'UTF8'
);
"""

try:
    with conn.cursor() as cursor:
        cursor.execute(
            "TRUNCATE TABLE public.clean_sales_transactions;"
        )

        with open(
            csv_path,
            mode="r",
            encoding="utf8",
            newline=""
        ) as csv_file:
            cursor.copy_expert(
                copy_sql,
                csv_file
            )

    conn.commit()
    print("Import completed successfully")

except Exception as error:
    conn.rollback()
    print("Import failed")
    print(error)

Import completed successfully

In [3]:
with conn.cursor() as cursor:
    cursor.execute("""
        SELECT COUNT(*)
        FROM public.clean_sales_transactions;
    """)

    total_rows = cursor.fetchone()[0]

print(
    "PostgreSQL rows:",
    f"{total_rows:,}"
)

PostgreSQL rows: 1,029,609

In [4]:
with conn.cursor() as cursor:
    cursor.execute("""
        SELECT
            COUNT(*) AS total_rows,
            COUNT(DISTINCT invoice) AS unique_invoices,
            COUNT(DISTINCT customer_id) AS unique_customers,
            ROUND(SUM(line_revenue), 2) AS total_revenue,
            MIN(invoice_date) AS first_sale,
            MAX(invoice_date) AS last_sale
        FROM public.clean_sales_transactions;
    """)

    database_summary = cursor.fetchone()

print("Total rows:", f"{database_summary[0]:,}")
print("Unique invoices:", f"{database_summary[1]:,}")
print("Unique customers:", f"{database_summary[2]:,}")
print("Total revenue:", database_summary[3])
print("First sale:", database_summary[4])
print("Last sale:", database_summary[5])

Total rows: 1,029,609
Unique invoices: 40,077
Unique customers: 5,878
Total revenue: 20913891.47
First sale: 2009-12-01 07:45:00
Last sale: 2011-12-09 12:50:00